"""Add author, sources, artifacts, and AI assistance fields to learning content

Revision ID: acf408ade49f
Revises: d26e1e2d1cb6
Create Date: 2025-06-30 20:36:16.795772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf408ade49f'
down_revision = 'd26e1e2d1cb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_content', sa.Column('author', sa.String(), nullable=True))
    op.add_column('learning_content', sa.Column('co_authors', sa.JSON(), nullable=True))
    op.add_column('learning_content', sa.Column('sources', sa.Text(), nullable=True))
    op.add_column('learning_content', sa.Column('artifacts', sa.Text(), nullable=True))
    op.add_column('learning_content', sa.Column('ai_assisted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_content', 'ai_assisted')
    op.drop_column('learning_content', 'artifacts')
    op.drop_column('learning_content', 'sources')
    op.drop_column('learning_content', 'co_authors')
    op.drop_column('learning_content', 'author')
    # ### end Alembic commands ###