"""Initial migration

Revision ID: d26e1e2d1cb6
Revises: 
Create Date: 2025-06-30 08:17:29.384035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26e1e2d1cb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('difficulty_tier', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('test_cases', sa.JSON(), nullable=True),
    sa.Column('solution_template', sa.Text(), nullable=True),
    sa.Column('knowledge_area', sa.String(), nullable=False),
    sa.Column('subtopics', sa.JSON(), nullable=True),
    sa.Column('personas', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('hints', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('analytics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_title', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('personas', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('sandbox_type', sa.String(), nullable=False),
    sa.Column('aws_services', sa.JSON(), nullable=True),
    sa.Column('technical_requirements', sa.JSON(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('cost_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_status', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_title')
    )
    op.create_table('learning_pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_persona', sa.String(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_prerequisites',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_content.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['learning_content.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'prerequisite_id')
    )
    op.create_table('content_questions',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_content.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'question_id')
    )
    op.create_table('pathway_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_content.id'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['learning_pathways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('estimate_type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('compute_cost', sa.Float(), nullable=True),
    sa.Column('storage_cost', sa.Float(), nullable=True),
    sa.Column('network_cost', sa.Float(), nullable=True),
    sa.Column('managed_services_cost', sa.Float(), nullable=True),
    sa.Column('other_costs', sa.Float(), nullable=True),
    sa.Column('cost_factors', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['learning_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_dependencies',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['assessment_questions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'dependency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_dependencies')
    op.drop_table('pricing_estimates')
    op.drop_table('pathway_items')
    op.drop_table('content_questions')
    op.drop_table('content_prerequisites')
    op.drop_table('learning_pathways')
    op.drop_table('learning_content')
    op.drop_table('assessment_questions')
    # ### end Alembic commands ###